FaziletOto.MVC.UI/Controllers/AccountController.cs
using FaziletOto.BLL.Data.EF.Service;
using FaziletOto.CORE.Contants;
using FaziletOto.DOMAIN.Entities;
using FaziletOto.DTOs.UserDTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FaziletOto.MVC.UI.Controllers
{
    public class AccountController : Controller
    {
        private readonly IUserService userManager;

        public AccountController(IUserService _usermanager)
        {
            userManager = _usermanager;
        }

        [HttpPost]
        public ActionResult LoginPost(LoginUserDto loginUserDto)
        {
            if (ModelState.IsValid)
            {
                var loginReturn = userManager.Login(loginUserDto.Email, loginUserDto.Password);
                if (loginReturn.ReturnTitle == ReturnTitle.Success)
                {
                    User user = loginReturn.Data;
                    user.LoginKey = Guid.NewGuid();
                    var updateReturn = userManager.Update(user);
                    if (updateReturn.ReturnTitle == ReturnTitle.Success)
                    {
                        //ID
                        HttpCookie cookieID = new HttpCookie("FaziletOto_UserID");
                        cookieID.Value = user.ID.ToString();
                        cookieID.Expires = DateTime.Now.AddDays(5);
                        Response.Cookies.Add(cookieID);
                        //Username
                        HttpCookie cookieUsername = new HttpCookie("FaziletOto_Username");
                        cookieUsername.Value = user.Username.ToString();
                        cookieUsername.Expires = DateTime.Now.AddDays(5);
                        Response.Cookies.Add(cookieUsername);
                        //LoginKey
                        HttpCookie cookieKey = new HttpCookie("FaziletOto_UserLoginKey");
                        cookieKey.Value = user.LoginKey.ToString();
                        cookieKey.Expires = DateTime.Now.AddDays(5);
                        Response.Cookies.Add(cookieKey);
                    }
                }
            }
            return RedirectToAction("HomePage", "Home");
        }
    }
}

FaziletOto.MVC.UI/Controllers/AdminCategoryController.cs
using AutoMapper;
using FaziletOto.DOMAIN.Entities;
using FaziletOto.DTOs.CategoryDTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Web;
using System.Web.Mvc;

namespace FaziletOto.MVC.UI.Controllers
{
    public class AdminCategoryController : Controller
    {
        [HttpGet]
        public ActionResult AdminCategoryPage()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AdminCategoryAddPage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AdminCategoryAddPage(AddProductCategoryDto addProductCategoryDto)
        {
            ProductCategory category = Mapper.Map<ProductCategory>(addProductCategoryDto);
            // TODO : after user
            return RedirectToAction("AdminCategoryPage", "AdminCategory");
        }

        [HttpGet]
        public ActionResult AdminCategoryArrangePage()
        {
            return View();
        }
    }
}

FaziletOto.MVC.UI/Controllers/AdminCommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FaziletOto.MVC.UI.Controllers
{
    public class AdminCommonController : Controller
    {
        public PartialViewResult RenderSidebar(string pageTitle)
        {
            return PartialView("~/Views/Shared/AdminSidebarPartial.cshtml",pageTitle);
        }
    }
}

FaziletOto.MVC.UI/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FaziletOto.MVC.UI.Controllers
{
    public class AdminHomeController : Controller
    {
        public ActionResult AdminHomePage()
        {
            return View();
        }
    }
}

FaziletOto.MVC.UI/Controllers/AdminUserController.cs
using AutoMapper;
using FaziletOto.BLL.Data.EF.Service;
using FaziletOto.CORE.Contants;
using FaziletOto.DOMAIN.Entities;
using FaziletOto.DTOs.UserDTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FaziletOto.MVC.UI.Controllers
{
    public class AdminUserController : Controller
    {
        private readonly IUserService userManager;

        public AdminUserController(IUserService _userManager)
        {
            userManager = _userManager;
        }

        [HttpGet]
        public ActionResult AdminUserPage()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AdminUserAddPage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AdminUserAddPage(AddUserDto addUserDto)
        {
            if (ModelState.IsValid)
            {
                User user = Mapper.Map<User>(addUserDto);
                var baseReturn = userManager.AddUserAsAdmin(user);
                return RedirectToAction("AdminUserPage", "AdminUser");        
            }
            return View(addUserDto);
        }

        [HttpGet]
        public ActionResult AdminUserArrangePage()
        {
            var model = userManager.Gets();
            return View(model.Data);
        }

        [HttpPost]
        public JsonResult AdminUserUpdateAjax(UpdateUserDto updateUserDto)
        {
            if (ModelState.IsValid)
            {
                User updateUser = Mapper.Map<User>(updateUserDto);
                var json = userManager.UpdateUserAsAdmin(updateUser);
                return Json(json);
            }
            else
            {
                var json = new Dictionary<string, object>();
                json.Add("Result", false);
                return Json(json);
            }
        }

        [HttpPost]
        public JsonResult AdminUserDeleteAjax(int ID)
        {
            var baseResult = userManager.UpdateDeletion(userManager.Get(x => x.ID == ID).Data);
            Dictionary<string, object> dictionary = new Dictionary<string, object>();
            dictionary.Add("ID", ID.ToString());
            return Json(dictionary);
        }
    }
}

FaziletOto.MVC.UI/Controllers/CommonController.cs
using FaziletOto.BLL.Data.EF.Service;
using FaziletOto.DOMAIN.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FaziletOto.MVC.UI.Controllers
{
    public class CommonController : Controller
    {

        private readonly IUserService userManager;

        public CommonController(IUserService _userManager)
        {
            userManager = _userManager;
        }

        public PartialViewResult RenderNavbar()
        {
            User user = null;
            if (Request.Cookies.Get("FaziletOto_UserLoginKey") != null)
            {
                string loginKeyS = Request.Cookies.Get("FaziletOto_UserLoginKey").Value;
                Guid loginKey = Guid.Parse(loginKeyS);
                var loginReturn = userManager.Get(x => x.LoginKey == loginKey);
                user = loginReturn.Data;
            }
            return PartialView("~/Views/Shared/NavbarPartial.cshtml", user);
        }
    }
}

FaziletOto.MVC.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FaziletOto.MVC.UI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult HomePage()
        {
            return View();
        }
    }
}

FaziletOto.MVC.UI/Views/AdminCategory/AdminCategoryPage.cshtml
@{
    ViewBag.Title = "Yönetim/Ürün Kategori";
    Layout = "~/Views/Shared/AdminMainLayout.cshtml";
}

FaziletOto.MVC.UI/Views/AdminHome/AdminHomePage.cshtml
@{
    ViewBag.Title = "Yönetim/Anasayfa";
    Layout = "~/Views/Shared/AdminMainLayout.cshtml";
}

<div class="container container-fluid">
    <div class="row">
        <div class="col-6 mt-3">
            <div class="card rounded-bottom w-100 h-100">
                <div class="card-body p-0 m-0">
                    <h4 class="bg-danger rounded-bottom w-100 m-0 text-white text-center p-2">Kullanıcı Özeti</h4>
                    <div class="p-2 mb-5">
                        <table class="table table-borderless">
                            <tr>
                                <th>Görev</th>
                                <th>Görevli Sayısı</th>
                            </tr>
                            <tr>
                                <td>Admin</td>
                                <td>0</td>
                            </tr>
                            <tr>
                                <td>Stok</td>
                                <td>0</td>
                            </tr>
                            <tr>
                                <td>Satış</td>
                                <td>0</td>
                            </tr>
                        </table>
                    </div>
                    <div class="w-100 text-right position-absolute" style="bottom:0;right:0">
                        <a href="#" class="btn btn-primary w-50 text-center m-2" style="font-size:0.75em">İşlem</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6 mt-3">
            <div class="card rounded-bottom w-100 h-100">
                <div class="card-body p-0">
                    <h4 class="bg-danger rounded-bottom w-100 m-0 text-white text-center p-2">Ürün Özeti</h4>
                    <div class="p-2 mb-5">
                        <table class="table table-borderless mb-0">
                            <tr>
                                <th></th>
                                <th>Ürün Sayısı</th>
                            </tr>
                            <tr>
                                <th>Toplam</th>
                                <td>0</td>
                            </tr>
                            <tr>
                                <th>Stok Durumu(<%50)</th>
                                <td>0</td>
                            </tr>
                            <tr>
                                <th>Stok Durumu(<%25)</th>
                                <td>0</td>
                            </tr>
                            <tr>
                                <th>Stok Durumu(<%10)</th>
                                <td>0</td>
                            </tr>
                            <tr>
                                <th>Stok Durumu(<%5)</th>
                                <td>0</td>
                            </tr>
                        </table>
                        <h5 class="text-center">*Ürünsel bazda hesaplanmıştır.</h5>
                    </div>
                    <div class="w-100 text-right position-absolute" style="bottom:0;right:0">
                        <a href="#" class="btn btn-primary w-50 text-center m-2" style="font-size:0.75em">İşlem</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 mt-3">
            <div class="card rounded-bottom w-100 h-100">
                <div class="card-body p-0">
                    <h4 class="bg-danger rounded-bottom w-100 m-0 text-white text-center p-2">Kategori Özeti</h4>
                    <div class="p-2 mb-5">
                        <table class="table table-borderless mb-0">
                            <tr>
                                <th>Kategori Adı</th>
                                <th>Ait Ürün Sayısı</th>
                            </tr>
                            <tr>
                                <td>CategoryA</td>
                                <td>0</td>
                            </tr>
                            <tr>
                                <td>CategoryB</td>
                                <td>0</td>
                            </tr>
                        </table>
                    </div>
                    <div class="w-100 text-right position-absolute" style="bottom:0;right:0">
                        <a href="#" class="btn btn-primary w-25 text-center m-2" style="font-size:0.75em">İşlem</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6 mt-3">
            <div class="card rounded-bottom w-100 h-100">
                <div class="card-body p-0">
                    <h4 class="bg-danger rounded-bottom w-100 m-0 text-white text-center p-2">Müşteri Özeti</h4>
                    <div class="p-2 mb-5">
                        <table class="table table-borderless mb-0">
                            <tr>
                                <th>Onaylanmış</th>
                                <td>0</td>
                            </tr>
                            <tr>
                                <th>Bekleyen</th>
                                <td>0</td>
                            </tr>
                        </table>
                    </div>
                    <div class="w-100 text-right position-absolute" style="bottom:0;right:0">
                        <a href="#" class="btn btn-primary w-50 text-center m-2" style="font-size:0.75em">İşlem</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6 mt-3">
            <div class="card rounded-bottom w-100 h-100">
                <div class="card-body p-0">
                    <h4 class="bg-danger rounded-bottom w-100 m-0 text-white text-center p-2">Sipariş Özeti</h4>
                    <div class="p-2 mb-5">
                        <table class="table table-borderless mb-0">
                            <tr>
                                <th>Durum</th>
                                <th>Sayı</th>
                            </tr>
                            <tr>
                                <td>Onaylanmış</td>
                                <td>0</td>
                            </tr>
                            <tr>
                                <td>İptal Edilmiş</td>
                                <td>0</td>
                            </tr>
                            <tr>
                                <td>Bekleyen</td>
                                <td>0</td>
                            </tr>
                        </table>
                    </div>
                    <div class="w-100 text-right position-absolute" style="bottom:0;right:0">
                        <a href="#" class="btn btn-primary w-50 text-center m-2" style="font-size:0.75em">İşlem</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

FaziletOto.MVC.UI/Views/AdminUser/AdminUserAddPage.cshtml
@model AddUserDto

@{
    ViewBag.Title = "Yönetim/Kullanıcılar/Ekle";
    Layout = "~/Views/Shared/AdminMainLayout.cshtml";
}

<h6 class="h6 text-center">Şirkete "Admin", "Stok Personeli" ve "Satış Personeli eklemek için kullanılacaktır.</h6>
<div class="container">
    @{Html.BeginForm("AdminUserAddPage", "AdminUser", FormMethod.Post, new { @class = "form-group mt-4" }); }
    @Html.AntiForgeryToken()
    <div class="row m-0 p-0">
        <div class="col-12 mt-2">
            @Html.ValidationSummary("", new { @class = "text-danger" })
        </div>
        <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6 mt-2">
            @Html.LabelFor(x => x.Name)
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control", required = "required", min = "2", max = "50", type = "text" })
        </div>
        <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6 mt-2">
            @Html.LabelFor(x => x.Surname)
            @Html.TextBoxFor(x => x.Surname, new { @class = "form-control", required = "required", min = "2", max = "50", type = "text" })
        </div>
        <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6 mt-2">
            @Html.LabelFor(x => x.Username)
            @Html.TextBoxFor(x => x.Username, new { @class = "form-control", required = "required", min = "8", max = "15", type = "text" })
        </div>
        <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6 mt-2">
            @Html.LabelFor(x => x.Email)
            @Html.TextBoxFor(x => x.Email, new { @class = "form-control", required = "required", min = "8", max = "100", type = "email" })
        </div>
        <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6 mt-2">
            @Html.LabelFor(x => x.Password)
            @Html.TextBoxFor(x => x.Password, new { @class = "form-control", required = "required", min = "8", max = "20", type = "password" })
        </div>
        <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6 mt-2">
            @Html.LabelFor(x => x.PasswordCheck)
            @Html.TextBoxFor(x => x.PasswordCheck, new { @class = "form-control", required = "required", min = "8", max = "20", type = "password" })
        </div>
        <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4 mt-4">
            <div class="w-50 float-left">
                @Html.LabelFor(x => x.IsAdmin)
            </div>
            <div class="w-50 float-left">
                @Html.CheckBoxFor(x => x.IsAdmin, new { @class = "form-check-input", type = "checkbox" })
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4 mt-4">
            <div class="w-50 float-left">
                @Html.LabelFor(x => x.IsSalesman)
            </div>
            <div class="w-50 float-left">
                @Html.CheckBoxFor(x => x.IsSalesman, new { @class = "form-check-input", type = "checkbox" })
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4 mt-4">
            <div class="w-50 float-left">
                @Html.LabelFor(x => x.IsStockKeeper)
            </div>
            <div class="w-50 float-left">
                @Html.CheckBoxFor(x => x.IsStockKeeper, new { @class = "form-check-input", type = "checkbox" })
            </div>
        </div>
        <div class="col-12 mt-4 mb-3 text-center">
            <input class="btn btn-success w-25" value="Kaydet" type="submit" style="min-width:200px" />
        </div>
    </div>
    @{Html.EndForm();}



</div>

FaziletOto.MVC.UI/Views/AdminUser/AdminUserPage.cshtml
@{
    ViewBag.Title = "Yönetim/Kullanıcılar";
    Layout = "~/Views/Shared/AdminMainLayout.cshtml";
}

FaziletOto.MVC.UI/Views/Home/HomePage.cshtml
@{
    ViewBag.Title = "Anasayfa";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

FaziletOto.MVC.UI/Views/Shared/AdminMainLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Html.Partial("~/Views/Shared/ExtensionPartial.cshtml")
</head>
<body>
    <div>
        @{Html.RenderAction("RenderSidebar", "AdminCommon", new {pageTitle = (string)ViewBag.Title });}
    </div>
    <div id="main">
        <div class="w3-teal">
            <div class="row bg-dark m-0 p-0">
                <button id="openNav" class="btn btn-dark w3-xlarge float-left" onclick="w3_open()">&#9776;</button>
                <div class="w3-container float-left">
                    <h2>@ViewBag.Title</h2>
                </div>
            </div>
        </div>
        <div class="w3-container">
            @RenderBody()
        </div>
    </div>
    @RenderSection("Script", false)
</body>
</html>

FaziletOto.MVC.UI/Views/Shared/AdminSidebarPartial.cshtml
@model string

    <div class="w3-sidebar w3-bar-block w3-card w3-animate-left bg-dark" style="display:none" id="mySidebar">
        <button class="w3-bar-item w3-button w3-large text-right float-right" onclick="w3_close()">
            <span class="badge badge-dark pt-1" style="font-size:1.6em">&times;</span>
        </button>
        <a href="@Url.Action("AdminHomePage","AdminHome")" class="w3-bar-item w3-button text-decoration-none text_Sidebar @(Model.Contains("Anasayfa")?"text-warning":"")"><span class="fa fa-home"></span> Anasayfa</a>
        <div class="btn-group dropdown w-100">
            <a href="@Url.Action("AdminUserPage","AdminUser")" class="w3-bar-item w3-button text-decoration-none text_Sidebar @(Model.Contains("Kullanıcılar")?"text-warning":"")"><span class="fa fa-user"></span> Kullanıcılar</a>
            <button type="button" class="btn rounded" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="fa fa-chevron-down text-white"></span>
            </button>
            <div class="dropdown-menu bg-dark" style="color:black">
                <a class="dropdown-item w-100 text_SidebarSub" href="@Url.Action("AdminUserAddPage","AdminUser")">Ekle</a>
                <a class="dropdown-item w-100 text_SidebarSub" href="@Url.Action("AdminUserArrangePage","AdminUser")">Düzenle</a>
            </div>
        </div>

        <div class="btn-group dropdown w-100">
            <a href="@Url.Action("AdminCategoryPage","AdminCategory")" class="w3-bar-item w3-button text-decoration-none text_Sidebar @(Model.Contains("Kategori")?"text-warning":"")"><span class="fa fa-user"></span> Ürün Kategori</a>
            <button type="button" class="btn rounded" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="fa fa-chevron-down text-white"></span>
            </button>
            <div class="dropdown-menu bg-dark" style="color:black">
                <a class="dropdown-item w-100 text_SidebarSub" href="@Url.Action("AdminCategoryAddPage","AdminCategory")">Ekle</a>
                <a class="dropdown-item w-100 text_SidebarSub" href="@Url.Action("AdminCategoryArrangePage","AdminCategory")">Düzenle</a>
            </div>
        </div>

        <div class="btn-group dropdown w-100">
            <a href="@Url.Action("AdminProductPage","AdminProduct")" class="w3-bar-item w3-button text-decoration-none text_Sidebar @(Model.Contains("Ürün")&&!Model.Contains("Kategori")?"text-warning":"")"><span class="fa fa-user"></span> Ürün</a>
            <button type="button" class="btn rounded" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="fa fa-chevron-down text-white"></span>
            </button>
            <div class="dropdown-menu bg-dark" style="color:black">
                <a class="dropdown-item w-100 text_SidebarSub" href="@Url.Action("AdminProductAddPage","AdminProduct")">Ekle</a>
                <a class="dropdown-item w-100 text_SidebarSub" href="@Url.Action("AdminProductArrangePage","AdminProduct")">Düzenle</a>
            </div>
        </div>
    </div>

FaziletOto.MVC.UI/Views/Shared/ExtensionPartial.cshtml
<link href="~/Content/bootstrapCSS/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/CSS/AdminSidebar.css" rel="stylesheet" />
<link href="~/Content/fontAwesome/css/font-awesome.css" rel="stylesheet" />

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="~/Content/JS/AdminSidebar.js"></script>
<script src="~/Content/Jquery/jquery.js"></script>

FaziletOto.MVC.UI/Views/Shared/MainLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Html.Partial("ExtensionPartial")
</head>
<body>
    @{Html.RenderAction("RenderNavbar", "Common");}
    @RenderBody()
</body>
</html>

FaziletOto.MVC.UI/Views/Shared/NavbarPartial.cshtml
@model User

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            @{
                if (Model == null)
                {
                    <li class="nav-item">
                        <button type="button" class="btn btn-primary nav-item" data-toggle="modal" data-target="#loginModal">
                            Login
                        </button>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <span class="nav-link">@Model.Username |</span>
                    </li>
                    if (Model.IsAdmin)
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("AdminHomePage","AdminHome")">Yönetim</a>
                        </li>
                    }
                }
            }

        </ul>
    </div>
</nav>
<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header text-center w-100">
                <h5 class="modal-title text-center w-100" id="loginModalLabel">Login</h5>
            </div>
            <div class="modal-body">
                @{Html.BeginForm("LoginPost", "Account", FormMethod.Post, new { @class = "form-group" });}
                <input name="Email" class="form-control w-100" type="email" required="required" placeholder="E-posta" />
                <input name="Password" class="form-control w-100" type="password" required="required" placeholder="Şifre" />
                <div class="w-100 text-center">
                    <input class="btn btn-primary w-50" type="submit" />
                </div>
                @{Html.EndForm();}
            </div>
        </div>
    </div>
</div>